export const TRANSLATIONS = {
  es: {
    connecting: "Conectando...",
    refresh: "Actualizar",
    language: "ES",
    errorTitle: "Error de Conexión",
    retry: "Reintentar",
    phrases: [
      "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
      "El único modo de hacer un gran trabajo es amar lo que haces.",
      "La innovación distingue entre un líder y un seguidor.",
      "No cuentes los días, haz que los días cuenten.",
      "El futuro pertenece a quienes creen en la belleza de sus sueños.",
      "La creatividad es la inteligencia divirtiéndose.",
      "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.",
      "La única forma de hacer algo bien es hacerlo con pasión.",
      "Los sueños no tienen fecha de caducidad.",
      "La vida comienza al final de tu zona de confort.",
      "Un verdadero artista no es el que se inspira, sino quien inspira a otros. — Salvador Dalí",
      "Los hombres geniales empiezan grandes obras, los hombres trabajadores las terminan. — Leonardo da Vinci",
      "Enviar luz al corazón del hombre, ese es el deber de un artista. — Robert Schumann",
      "El arte es una aventura que nos lleva a un mundo desconocido… nuestra tarea como artista es hacer que la gente vea el mundo tal como lo vemos nosotros. — Mark Rothko",
      "El artista es la mano que, mediante una y otra tecla, hace vibrar adecuadamente el alma humana. — Wassily Kandinski",
      "Contra toda opinión, no son los pintores, sino los espectadores quienes hacen los cuadros. — Marcel Duchamp",
      "Un artista intenta que la gente se acerque a las cosas, ya que el arte tiene que ver con el hecho de compartir. — David Hockney",
      "Un artista es alguien que produce cosas que la gente no necesita tener pero que él, por alguna razón, piensa que sería una buena idea darles. — Andy Warhol",
      "Sueño con pintar y luego pinto mis sueños. — Vincent van Gogh",
      "Haz lo que sea necesario para hacer realidad tu deseo más importante, y al final acabarás por lograrlo. — Ludwig van Beethoven",
      "Se requiere valor para crear un mundo propio. — Georgia O'Keeffe",
      "Todo lo que puedas imaginar es real. — Pablo Picasso",
      "Un lienzo en blanco tiene posibilidades ilimitadas. — Stephanie Perkins",
      "El color es mi obsesión diaria, mi alegría y mi tormento. — Claude Monet",
      "El artista sabe lo que hace, pero para que merezca la pena debe saltar esa barrera y hacer lo que no sabe. — Eduardo Chillida",
      "Nada es más nocivo para la creatividad que el furor de la inspiración. — Umberto Eco",
      "El artista debe disponer de mucho tiempo, tiempo libre, para no hacer nada, simplemente sentarse y dejar que las ideas sobrevengan. — Mark Rothko",
      "Aprende las reglas como un profesional para poder romperlas como un artista. — Pablo Picasso",
      "Vivir es como avanzar por un museo: después es cuando empiezas a entender lo que has visto. — Audrey Hepburn",
      "La vida es todo aquello que pasa, mientras uno está ocupado haciendo otra cosa. — John Lennon",
      "Amarse a uno mismo es el comienzo de un idilio que durará toda la vida. — Oscar Wilde",
      "Quien ha empezado a vivir más seriamente por dentro, empieza a vivir más sencillamente por fuera. — Ernest Hemingway",
      "Sin memoria no existimos; sin responsabilidad, quizá no merezcamos existir. — José Saramago",
      "El secreto de la existencia no consiste solamente en vivir, sino en saber para qué se vive. — Fiódor Dostoievski",
      "Pasamos por la vida. Mudamos la piel. Nos convertimos en nosotros mismos. — Patti Smith",
      "Nuestras vidas se definen por las oportunidades, incluso las que perdemos. — F. Scott Fitzgerald",
      "Aunque parezca paradójico, la vida imita al arte mucho más que el arte imita a la vida. — Oscar Wilde",
      "La vida es un lienzo en blanco, y debes lanzar sobre él toda la pintura que puedas. — Danny Kaye",
      "La vida late y aplasta el alma y el arte te recuerda que tienes una. — Stella Adler",
      "Me pinto a mí misma porque soy a quien mejor conozco. — Frida Kahlo",
      "Un artista es capaz de mostrar cosas que a otras personas les aterraría expresar. — Louise Bourgeois",
      "Una persona se mide por la soledad que puede aguantar. — Maruja Mallo",
      "Nadie me escuchó hasta que no supieron quién era. — Banksy",
      "Quien es inteligente solo quiere aprender, mientras que el resto busca enseñar. — Antón Chéjov",
      "Usas un espejo de cristal para ver tu cara; usas obras de arte para ver tu alma. — George Bernard Shaw",
      "El arte y el amor son lo mismo: es el proceso de verse en cosas que no son ustedes. — Chuck Klosterman",
      "Sólo el arte y la música tienen el poder de traer la paz. — Yoko Ono",
      "El arte deriva de un deseo de la persona para comunicarse con otro. — Edvard Munch",
      "El arte no es lo que ves, sino lo que haces que otros vean. — Edgar Degas",
      "El arte es una mentira que nos hace darnos cuenta de la verdad. — Pablo Picasso",
      "El arte es comunicación y permite que personas de diferentes culturas y épocas confluyan entre sí. — Anónimo",
      "Los artistas son los que permiten a la humanidad soportar la vida. — Anónimo",
      "El arte tiene que ver con el hecho de compartir; no se puede ser artista si no se quiere compartir una experiencia. — David Hockney",
      "El arte nos recuerda lo que significa ser humanos. — Anónimo",
      "La creatividad requiere tener el valor de desprenderse de las certezas. — Erich Fromm",
      "La inspiración existe, pero tiene que encontrarte trabajando. — Pablo Picasso",
      "El arte limpia del alma el polvo de la vida cotidiana. — Bertolt Brecht",
      "La originalidad no consiste en decir cosas nuevas, sino en decirlas como nadie las ha dicho antes. — Johann Wolfgang von Goethe",
      "El arte es la expresión de los más profundos pensamientos por el camino más sencillo. — Albert Einstein"
    ]
  },
  en: {
    connecting: "Connecting...",
    refresh: "Refresh",
    language: "EN",
    errorTitle: "Connection Error",
    retry: "Retry",
    phrases: [
      "Life is what happens while you're busy making other plans.",
      "The only way to do great work is to love what you do.",
      "Innovation distinguishes between a leader and a follower.",
      "Don't count the days, make the days count.",
      "The future belongs to those who believe in the beauty of their dreams.",
      "Creativity is intelligence having fun.",
      "Success is going from failure to failure without losing enthusiasm.",
      "The only way to do something well is to do it with passion.",
      "Dreams don't have an expiration date.",
      "Life begins at the end of your comfort zone.",
      "A true artist is not one who is inspired, but one who inspires others. — Salvador Dalí",
      "Brilliant men begin great works; industrious men finish them. — Leonardo da Vinci",
      "To send light into the darkness of men's hearts, that is the duty of the artist. — Robert Schumann",
      "Art is an adventure into a world unknown... our task as an artist is to make people see the world as we see it. — Mark Rothko",
      "The artist is the hand that plays the keyboard of the human soul. — Wassily Kandinski",
      "It is not the painters' business to make paintings. It is the spectators' business. — Marcel Duchamp",
      "An artist can make a connection with any audience by trying things that people haven't seen before. — David Hockney",
      "An artist is someone who produces things that people do not need to have but that he, for some reason, thinks it would be a good idea to give them. — Andy Warhol",
      "I dream my painting and I paint my dream. — Vincent van Gogh",
      "Do whatever is necessary to accomplish your most important desire, and eventually you will achieve it. — Ludwig van Beethoven",
      "It takes courage to create a world of your own. — Georgia O'Keeffe",
      "Everything you can imagine is real. — Pablo Picasso",
      "A blank canvas has unlimited possibilities. — Stephanie Perkins",
      "Color is my day-long obsession, joy and torment. — Claude Monet",
      "The artist knows what he does, but to be worthy of merit he must leap that barrier and do what he does not know. — Eduardo Chillida",
      "Nothing is more harmful to creativity than the fury of inspiration. — Umberto Eco",
      "The artist must have much time and much freedom to sit and do nothing, simply let ideas come. — Mark Rothko",
      "Learn the rules like a professional so you can break them like an artist. — Pablo Picasso",
      "Living is like walking through a museum: only afterward do you realize what you have seen. — Audrey Hepburn",
      "Life is what happens to you while you're busy making other plans. — John Lennon",
      "To love oneself is the beginning of a lifelong romance. — Oscar Wilde",
      "Anyone who has ever lived seriously by inner conviction, begins to live more simply outwardly. — Ernest Hemingway",
      "Without memory, we do not exist. Without accountability, perhaps we do not deserve to exist. — José Saramago",
      "The secret of existence consists not only in living but in knowing for what one lives. — Fiódor Dostoievski",
      "We walk through life. We shed our skin. We become ourselves. — Patti Smith",
      "Our lives are defined by opportunities, even the ones we miss. — F. Scott Fitzgerald",
      "Paradoxically, life imitates art far more than art imitates life. — Oscar Wilde",
      "Life is a blank canvas, and you should throw all the paint on it you can. — Danny Kaye",
      "Life beats down and crushes the soul and art reminds you that you have one. — Stella Adler",
      "I paint myself because I am so often alone and because I am the subject I know best. — Frida Kahlo",
      "An artist is able to show things that other people are afraid to express. — Louise Bourgeois",
      "A person is measured by the solitude they can endure. — Maruja Mallo",
      "Nobody ever heard of me until they found out who I was. — Banksy",
      "Intelligent people only want to learn, but everyone else wants to teach. — Anton Chekhov",
      "You use a crystal mirror to look at your face; you use works of art to look at your soul. — George Bernard Shaw",
      "Art and love are the same thing: it's the process of seeing yourself in things that are not you. — Chuck Klosterman",
      "Only art and music can bring peace to the world. — Yoko Ono",
      "Art arises from a human desire to communicate. — Edvard Munch",
      "Art is not what you see, but what you make others see. — Edgar Degas",
      "Art is a lie that makes us realize truth. — Pablo Picasso",
      "Art is communication that allows people of different cultures and times to come together. — Anonymous",
      "Artists are the ones that allow humanity to bear life. — Anonymous",
      "Art is about sharing; you cannot be an artist if you don't want to share an experience. — David Hockney",
      "Art reminds us what it means to be human. — Anonymous",
      "Creativity requires the courage to let go of certainties. — Erich Fromm",
      "Inspiration exists, but it has to find you working. — Pablo Picasso",
      "Art cleans the soul of the dust of daily life. — Bertolt Brecht",
      "Originality does not consist in saying new things, but in saying them as no one has said them before. — Johann Wolfgang von Goethe",
      "Art is the expression of the deepest thoughts in the simplest way. — Albert Einstein"
    ]
  }
};